config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show]
  end

  resources :posts do
    resources :comments, only: %i[new create]
    resource :likes, only: [:create]
  end
end
 

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, User
    can :read, Post
    can :read, Comment
    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    can :manage, Post if user.is? :admin
    can :manage, Comment if user.is?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :post, foreign_key: 'post_id'

  after_create :increment_comment_posts_counter

  def increment_comment_posts_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :post, foreign_key: 'post_id'

  after_create :increment_like_posts_counter

  def increment_like_posts_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  after_create :increment_user_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def increment_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :authentication_keys => [:name]
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'

  validates :name, presence: true
  validates :role, inclusion: { in: %w[admin user], message: '%<value>s is not a valid role [admin, user]' }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_sign_up_params, if: :devise_controller?

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio role email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio email password current_password role])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @post = Post.includes(:comments).find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.includes(:comments).find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @post.decrement!(:comments_counter)
    @comment.destroy
    redirect_to user_post_path(current_user, @post), notice: 'Comment successfully deleted'
  end


  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:id])
    @like = Like.create(user: current_user, post: @post)

    if @like.persisted?
      flash[:success] = 'Liked successfully!'
      redirect_to user_post_path(current_user, @post)
    else
      flash[:alert] = 'Something went wrong'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @user = User.find(params[:user_id])
    @comments = @post.comments

    @index = (@user.posts.order(:created_at).pluck(:id).index(@post.id) + 1 if @user.posts.include?(@post))
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_posts_path(current_user)

    else
      flash[:alert] = 'Something went wrong'
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    post = Post.find(params[:id])

    post.comments.destroy_all
    post.likes.destroy_all
    if post.destroy
      flash[:success] = 'Post deleted successfully'
      redirect_to user_posts_path(@user)
    else
      flash.now[:error] = 'Error: Post could not be deleted'
      redirect_to user_post_path(@user, post)
    end
  end


  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="form-wrapper">
  <%= form_with(model: [@post, @post.comments.build]) do |f| %>
    <%= f.hidden_field :authenticity_token, value: form_authenticity_token %>
    <%= f.text_area :text, class: "textarea-comment", placeholder: "Write your comment here", rows: 10 %>
    <%= f.submit "Submit Comment", class: "submit-comment" %>
  <% end %>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<form action="<%= post_likes_path(post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Like">
</form>

app/views/posts/_new.html.erb
<div class="container">
  <%= form_with model: @post, class: "form-1" do |form| %>
    <%= form.label :title, "Title", class: "post-label" %>
    <%= form.text_field :title, class: "post-label-title" %>
    <%= form.label :text, "Post text", class: "post-label-text" %>
    <%= form.text_area :text, size: "70x5", class: "post-label-area" %>
    <div class="submit-post">
      <%= form.submit "Add new post" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="post-container">
  <span class="post-title"><%= link_to post.title, user_post_path(@user, post) %></span>
  <span class="post-bio"><%= post.text %></span>
  <span class="post-totalpost">Comments : <%= post.comments_counter %>, Likes : <%= post.likes_counter %></span>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<%= render partial: "users/header", locals: { user: @user } %>
<% @posts.each do |post| %>
  <%= render partial: "post", locals: { post: post } %>
  
  <div class="recent-comments">
  <% if post.recent_comments.any? %>
    <% post.recent_comments.each do |comment| %>
      <p><%= comment.user.name %>: <%= comment.text %></p>
      <% if can? :destroy, comment %>
      <%= button_to 'Delete Post', user_post_path(@user, @post), method: :delete, class: 'delete-post'%>
    <% end %>
    <% end %>
    <% else %>
        <div class="no-comment">No comment yet for this post</div>
    <% end %>
  </div>
<% end %>

<button class = "pagination"><%= link_to "Pagination", user_posts_path(@user) %></button>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<div class="post-details">
    <h3 class="comment-title">
      Post # <%= @index %>
      by <%= @user.name %>
    </h3>

    <div class="counter-wrapper">
      <p class="comment-count">Comments: <%= @post.comments.count %></p>
      <p class="like-count">Likes: <%= @post.likes.count %></p>
    </div>

    <p class="post-comment-1"><%= @post.text %></p>
  </div>

  <div class = "all-comments">
  <% if @post.comments.any? %>
    <% @post.comments.each do |comment| %>
      <p><%= comment.user.name %>:
      <%= comment.text %></p>
    <% end %>
    <% else %>
        <div class="no-comment">No comment</div>
    <% end %>
  </div>

  <div class="can-delete">
    <% if can? :destroy, comment %>
      <%= button_to 'Delete comment', user_post_comment_path(@post.author, @post, comment), method: :delete, class: 'delete-button'%>
    <% end %>
  </div>

<%= render partial: 'comments/comment', locals: { post: @post, comment: Comment.new } %>

app/views/users/_header.html.erb
<div class="container-header">
<div>
  <img src="<%= user.photo %>" class="user-photo">
  <div class="user-card-info">
    <div class="flex-col">
      <span class="header-title"><%= link_to user.name, user_path(user) %></span>
      <span class="user-totalpost">Number of posts: <%= user.posts_counter %></span>
    </div>
  </div>
</div>
</div>

app/views/users/_signup.html.erb
<% if user_signed_in? %>
  <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %> 

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= render partial: "header", locals: { user: user } %>
<% end %>

<%= render partial: "signup" %>

app/views/users/show.html.erb
<%= render partial: "header", locals: { user: @user } %>

<div class="gap-1">
  <div class="user-card">
    <span class="bio-title">Bio</span>
    <span class="user-bio"><%= @user.bio %></span>
  </div>
</div>

<div class="post-voloany">
  <% if @recent_posts.any? %>
    <% @recent_posts.each do |recent_post| %>
      <%= render partial: "posts/post", locals: { post: recent_post } %>
    <% end %>
    <% else %>
    <p class="no-post">No recent posts found for <%= @user.name %>.</p>
  <% end %>
</div>

<%= render partial: 'posts/new', locals: { post: @post } %>

  <button class="see-all-posts" >
  <%= link_to "See All Posts", user_posts_path(@user) %>
  </button>

<%= render partial: "signup" %>